// Generated by `wit-bindgen` 0.4.0. DO NOT EDIT!
#ifndef __BINDINGS_HANDLER_H
#define __BINDINGS_HANDLER_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

typedef struct {
  char*ptr;
  size_t len;
} handler_string_t;

typedef struct {
  uint16_t status;
  handler_string_t body;
} handler_response_t;

typedef struct {
  handler_string_t f0;
  handler_string_t f1;
} handler_tuple2_string_string_t;

typedef struct {
  handler_tuple2_string_string_t *ptr;
  size_t len;
} handler_list_tuple2_string_string_t;

typedef struct {
  handler_list_tuple2_string_string_t query_params;
} handler_request_t;

// Exported Functions from `handler`
void handler_handle(handler_request_t *req, handler_response_t *ret);

// Helper Functions

void handler_response_free(handler_response_t *ptr);
void handler_tuple2_string_string_free(handler_tuple2_string_string_t *ptr);
void handler_list_tuple2_string_string_free(handler_list_tuple2_string_string_t *ptr);
void handler_request_free(handler_request_t *ptr);
void handler_string_set(handler_string_t *ret, const char*s);
void handler_string_dup(handler_string_t *ret, const char*s);
void handler_string_free(handler_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
